<?php

namespace SuperAICore\Backends\Concerns;

use Symfony\Component\Process\Process;

/**
 * Windows large-argv workaround for CLIs that take the prompt as an
 * argv argument (Kimi `--prompt <text>`, Kiro positional, Copilot
 * `-p <text>`) — i.e. CLIs that do NOT read stdin.
 *
 * Why this exists:
 *   - Symfony Process always wraps Windows commands in `cmd /V:ON
 *     /E:ON /D /C "(...)"` regardless of whether you pass the
 *     command as an array or string. cmd.exe has a hard 8191-char
 *     command-line limit; markdown prompts > ~7K silently truncate
 *     and the CLI either fails to start or sees a corrupted prompt.
 *   - macOS/Linux argv limits (`getconf ARG_MAX`, typically 128K+)
 *     comfortably fit our typical 25K agent-task prompts.
 *
 * Strategy:
 *   - Non-Windows or short argv → plain `new Process($args, …)`.
 *   - Windows + long argv → write a `.ps1` that defines the argv
 *     as an array literal and invokes the binary via PowerShell's
 *     splat operator (`& $binary @args`). PowerShell's call
 *     operator goes straight to `CreateProcess` with the array,
 *     bypassing `cmd.exe` and hitting only the kernel-level Windows
 *     API limit (~32K), comfortably above our prompt sizes.
 *
 * Stdin-reading CLIs (Claude `claude -p`, Codex `codex exec -`,
 * Gemini with `--prompt ""`) should NOT use this trait — they
 * already avoid the argv problem by piping the prompt through
 * `Process::setInput()`. This helper is only for CLIs whose
 * argv MUST carry the prompt.
 */
trait LargeArgvSafeSpawn
{
    /**
     * Hard cmd.exe command-line cap is 8191 chars; Symfony adds ~80
     * chars of `cmd /V:ON /E:ON /D /C "(...)"` wrapping overhead and
     * each argv element gets quoted (+2..6 chars). Threshold below
     * is conservative — once any single argv element + binary path
     * approaches it, we route through the PowerShell wrapper.
     *
     * PHP 8.1 doesn't permit trait constants; expose as a method.
     */
    protected static function winArgvThreshold(): int
    {
        return 6500;
    }

    /**
     * Build a `Process` that's safe even when the combined argv
     * exceeds Windows' cmd.exe command-line limit.
     *
     * @param  string[]                $args  Full argv with binary at index 0.
     * @param  ?string                 $cwd
     * @param  array<string,string|false> $env
     */
    protected function buildLargeArgvSafeProcess(array $args, ?string $cwd = null, array $env = []): Process
    {
        $isWindows = PHP_OS_FAMILY === 'Windows';

        if (!$isWindows || !$this->argvExceedsWindowsLimit($args)) {
            return new Process($args, $cwd, $env);
        }

        $ps1Path = $this->writePowerShellArgvWrapper($args);

        // PowerShell wrapper script: `& <bin> @argv` splats each array
        // element to the binary as a separate argv, no cmd.exe in the
        // middle. -NoProfile keeps startup fast; -ExecutionPolicy
        // Bypass tolerates restrictive group policies on locked-down
        // hosts; -File runs the script file directly (vs -Command
        // which has its own length limit).
        return new Process(
            ['powershell.exe', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $ps1Path],
            $cwd,
            $env,
        );
    }

    /** @param string[] $args */
    private function argvExceedsWindowsLimit(array $args): bool
    {
        $total = 0;
        foreach ($args as $a) {
            $total += strlen((string) $a) + 3; // +3: quotes + space
            if ($total >= self::winArgvThreshold()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Emit a self-contained .ps1 that holds every argv element as a
     * single-quoted PowerShell string literal, then invokes the
     * binary with the splat operator. Single quotes are escaped by
     * doubling — PowerShell's only metachar in single-quoted
     * strings.
     *
     * @param  string[] $args
     */
    private function writePowerShellArgvWrapper(array $args): string
    {
        if (empty($args)) {
            throw new \InvalidArgumentException('LargeArgvSafeSpawn: empty argv');
        }
        $binary = array_shift($args);

        $lines = [];
        foreach ($args as $a) {
            $lines[] = "  '" . str_replace("'", "''", (string) $a) . "'";
        }

        $script  = "# auto-generated by SuperAICore LargeArgvSafeSpawn — safe to delete\n";
        $script .= "\$ErrorActionPreference = 'Stop'\n";
        $script .= "\$binary = '" . str_replace("'", "''", (string) $binary) . "'\n";
        $script .= "\$arguments = @(\n" . implode(",\n", $lines) . "\n)\n";
        $script .= "& \$binary @arguments\n";
        $script .= "exit \$LASTEXITCODE\n";

        $tmpDir = sys_get_temp_dir();
        $path = $tmpDir . DIRECTORY_SEPARATOR . 'saicore-argv-' . bin2hex(random_bytes(6)) . '.ps1';
        file_put_contents($path, $script);
        return $path;
    }
}
