<?php

namespace SuperAICore\Models;

use SuperAICore\Models\Concerns\HasConfigurablePrefix;
use Illuminate\Database\Eloquent\Model;

/**
 * FIX-mode skill evolution candidate — never auto-applied.
 *
 * Generated by SkillEvolver when a skill fails or its metrics degrade.
 * Each row is a proposed change a human reviews before applying.
 *
 * @property int $id
 * @property string $skill_name
 * @property string $trigger_type
 * @property int|null $execution_id
 * @property string $status
 * @property string|null $rationale
 * @property string|null $proposed_diff
 * @property string|null $proposed_body
 * @property string|null $llm_prompt
 * @property array|null $context
 * @property \Carbon\Carbon|null $reviewed_at
 * @property string|null $reviewed_by
 */
class SkillEvolutionCandidate extends Model
{
    use HasConfigurablePrefix;

    protected $table = 'skill_evolution_candidates';

    public const TRIGGER_FAILURE            = 'failure';
    public const TRIGGER_METRIC_DEGRADATION = 'metric_degradation';
    public const TRIGGER_MANUAL             = 'manual';

    public const STATUS_PENDING    = 'pending';
    public const STATUS_REVIEWING  = 'reviewing';
    public const STATUS_APPLIED    = 'applied';
    public const STATUS_REJECTED   = 'rejected';
    public const STATUS_SUPERSEDED = 'superseded';

    protected $fillable = [
        'skill_name',
        'trigger_type',
        'execution_id',
        'status',
        'rationale',
        'proposed_diff',
        'proposed_body',
        'llm_prompt',
        'context',
        'reviewed_at',
        'reviewed_by',
    ];

    protected $casts = [
        'context' => 'array',
        'reviewed_at' => 'datetime',
    ];

    public function execution()
    {
        return $this->belongsTo(SkillExecution::class, 'execution_id');
    }
}
